# Generated by Django 3.0.3 on 2020-02-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Reporter'),
        ),
    ]
