# Generated by Django 3.0.3 on 2020-03-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_customer_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
